### ISSUE TITLE
Make the show tabs a on/off switch

### ISSUE THREAD

**Issue by markoheijnen** [markoheijnen/tabify-edit-screen#58]

**Comment by markoheijnen** [comment]
See Feedback at http://customizewp.com/organize-post-edit-screen-tabify/

**Comment by markoheijnen** [comment]
Still needs some UI love

**Comment by lmartins** [comment]
@markoheijnen Just to let you know the current implementation doesn't update the toggle status in Safari. I'll try to get a fix in if can later today. Im absolutely under water with my schedule right now but this is so useful to me that I can help if I can. Thank you so much for the updates.

**Comment by markoheijnen** [comment]
Thats weird since safari is the only browser I work in. Which version do you run?

**Comment by markoheijnen** [comment]
Updated styling
