### ISSUE TITLE
When showing tabs, use filtered tab data

### ISSUE THREAD

**Issue by junander** [markoheijnen/tabify-edit-screen#64]
First off, amazing plugin, really a bonus for entity types that have a lot of custom fields and/or meta boxes.

I'm trying to set up some tabs for just one specific page, and I've made it most of the way, by creating a fake 'post type' that uses the page slug to delineate a specific set of tabs for that page (i.e. it's stored in the 'tabify-edit-screen' option under ['poststypes']['page-*page-slug*'])

However I ran into a hitch when trying to get the tabs to work on the aforementioned page. After some digging, I traced the problem here, in show_tabs(), under edit-screen.php, lines 75 - 93:

```
$tabs = apply_filters( 'tabify_tab_posttype_tabs', $options[ $post_type ]['tabs'], $post_type );

$this->editscreen_tabs = new Tabify_Edit_Screen_Tabs( $tabs );
$default_metaboxes     = Tabify_Edit_Screen_Settings_Posttypes::get_default_items( $post_type );
$all_metaboxes         = array();

foreach ( $wp_meta_boxes[ $post_type ] as $priorities ) {
		foreach ( $priorities as $priority => $_metaboxes ) {
				foreach ( $_metaboxes as $metabox ) {
					if ( ! in_array( $metabox['id'], $default_metaboxes ) ) {
						$all_metaboxes[ $metabox['id'] ] = $metabox['title'];
					}
				}
			}
		}

$this->load_tabs();

foreach ( $options[ $post_type ]['tabs'] as $tab_index => $tab ) {
```

Using the tabify_tab_posttype_tabs filter, I was able to pull in the custom tabs for this specific page, however if you look at the loop iterating through the tabs (last line above), it actually uses the $options array, instead of using that filtered $tabs array. Is there a reason for this? Would it be possible to use the filtered $tabs array in that loop? I tried it on my dev build, and it seemed to work great, but obviously you know the plugin code far better than I do.

Another option: provide a filter on the $post_type used in 'tabify_tab_posttype_tabs', so I could inject a my fake 'post type', i.e something like this on line 52

`$post_type = apply_filters( 'tabify_tab_posttype', $screen->post_type)`

Thanks again for all your hard work on a fantastic plugin!

Joe

**Comment by markoheijnen** [comment]
That is indeed a good point and it was just an oversight when adding the filter. I will work on some rewrites in the next days and have the fix released on Sunday

**Comment by junander** [comment]
Amazing, thank you @markoheijnen!
