### ISSUE TITLE
Use closure instead of create_function

### ISSUE THREAD

**Issue by markoheijnen** [markoheijnen/tabify-edit-screen#65]

**Comment by miclgael** [comment]
Hi @markoheijnen - thank you very much for your work on the plug-in!
is there any chance this commit could be published as a plug-in update soon? 

[I think it might make a lot of folks happy! ](https://wordpress.org/support/plugin/tabify-edit-screen/)

Thanks,
MG

**Comment by markoheijnen** [comment]
I should have done that directly but I didn't :(. Hopefully I will be able to do it today
